name: vcr
description: A package to mock requests in tests, storing request in json files and reusing
version: 0.1.2
homepage: https://github.com/keviinlouis/vcr

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  mockito: ^5.2.0
  dio: ^4.0.6
  json_annotation: ^4.6.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.3.1
  lints: ^1.0.1
  test: ^1.19.5
